### PR TITLE
Object to JSON converter - review required

### PR DESCRIPTION
**Pull request by vernerkeel**
NB! 'Files changed ' näitab vaid viimase commiti muudatusi. Vaata aga terve kood üle. Tulevikus näed otse "files changed" alt lisatud koodi. 

Please review my code. 

1. Add it to your local machine. 
2. Read the readme, install it and try to convert an object to JSON. 
3. If any of the instructions provided are unclear or if something does not work, write those observations to the review. 
4. Try to understand the code. If some comments do not make sense, add them to the review. 
5. If you spot any errors or sloppiness, write about them in your review as well.

### CODE REVIEW

**Review by maarjaroots — COMMENTED** [review]
In the readme.md
1.Please update the Installation section: npm i (not npm start)
2. Please mention in the Instruction section that the user can create their own input file inside of the same folder.
3. Please mention where the JSON output is going to be displayed (You have mention it in the code comments, but also add it to the readme).


How to prevent a SyntaxError when the converted file is empty? Could there be some logic before the readFileSync method is being used?

The comments in your code are very helpful.

**Review by maarjaroots — APPROVED** [review]
This is more clearer now.

**Review by maarjaroots — APPROVED** [review]
I can understand now where to create the file

**Review by maarjaroots — APPROVED** [review]

**Review by maarjaroots — APPROVED** [review]
Now the user knows what to do when they have left the file empty.

**Review by maarjaroots — APPROVED** [review]
I can understand the logic.

**Review by vernerkeel — COMMENTED** [review]
Testing commenting.

**Comment by vernerkeel** [comment]
> Testing commenting.



> I can understand the logic.

Testing quoting from the code review.

**Comment by vernerkeel** [comment]
Testing commenting here.

**Pull request merged**
